/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Javavim */

#ifndef _Included_Javavim
#define _Included_Javavim
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Javavim
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Javavim_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
